### PR TITLE
chore: run a test on the deployed netlify url

### PR DESCRIPTION
**Pull request by lirantal**
WIP: experimenting with running Playwright on a PR's preview URL on Netlify

### CODE REVIEW

**Review by MichalPorag — APPROVED** [review]
Thank you :)

**Comment by MichalPorag** [comment]
@lirantal can you please resolve conflicts?

**Comment by lirantal** [comment]
@MichalPorag resolved but it is probably going to need to resolve another time after you merge #249

**Comment by lirantal** [comment]
@MichalPorag what is the actual issue that needs fixing? can't tell much from this, these are all set to warn.

image

**Comment by lirantal** [comment]
Also to note that when I run the linter check locally I get that everything's just fine:

```
npm run lint

> pull-request-community@0.1.0 lint
> next lint

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
✔ No ESLint warnings or errors
```

**Comment by lirantal** [comment]
@MichalPorag ready to merge 🙏🏼

**Comment by MichalPorag** [comment]
Hi @lirantal, thank you so much. Unfortunately still can't merge, too many changes... Please open in new PR. Closing it for now.

**Comment by lirantal** [comment]
I think it was ok but anyway I'll open a new PR one you merge the other one then :-)

**Pull request closed without merging**
