### PR TITLE
Removed `colors.ts` file

### LINKED ISSUE #158: Remove colors.ts file

### PR DESCRIPTION
**Pull request by soham4abc**
Fixes  #158

### CODE REVIEW

**Review by MichalPorag — CHANGES_REQUESTED** [review]
Hi! Thank you so much for your contribution.
To complete this task, you need to fix every place connected to this file, it is not enough to delete it. 

Also, please look at the contribution guide and ask to take this task on the issue's page so I can assign you.

**Comment by soham4abc** [comment]
PTAL @MichalPorag

**Review by MichalPorag — CHANGES_REQUESTED** [review]
Please use the get the colors from the colors.scss file instead of adding hard-coded values.

**Comment by soham4abc** [comment]
> Please use the get the colors from the colors.scss file instead of adding hard-coded values.

Can you please let me know the location of this particular file so that I can import it. That would be of great help

**Comment by MichalPorag** [comment]
@soham4abc We need this issue to be fixed quickly so I'm moving it to somebody from the community. thank you for your time.

**Pull request closed without merging**
