### PR TITLE
test: adding e2e tests

### PR DESCRIPTION
**Pull request by lirantal**
A couple more tests to give folks examples of how to use Playwright.

### CODE REVIEW

**Comment by MichalPorag** [comment]
@lirantal can you please resolve conflicts?

**Comment by lirantal** [comment]
@MichalPorag done ;-)

**Comment by MichalPorag** [comment]
@lirantal can you please fix eslint text?

**Comment by lirantal** [comment]
Same as the other PR

**Comment by lirantal** [comment]
Are you sure? looks ok to me 
image

**Comment by MichalPorag** [comment]
@lirantal yes, I'm sure:
https://www.facebook.com/groups/PullRequest/mentorship_application

**Comment by lirantal** [comment]
?

**Pull request merged**
